/*
** Suleyman Muhammad
** 
** ECE 8473: OSP
** Assignment 2 Problem #1
**
** Program generates output of a noisy sign wave with output suitable to plot.
** The noise is generated by the rand() function, coupled with our 
** calculations for f (frequency) phi (phase) and r (offset), which is *initialized with *srand(time(0)).
*/
 
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <time.h>
 
#define PI 4*atan(1)  /* Calculation of pi with high precision */
 
int main(void){
  int i;
  double val, r, phi, f; 
 

  srand(time(0));                                  /* Random initialization */
  f = 1000*( (rand()/(double)RAND_MAX) +1) + 1000; /* Frequency */
  phi = (2*PI)*( (rand()/(double)RAND_MAX) +1);    /* Phase */
 
  for(i=0; i < 101; ++i){
    r = 1.5*(rand()/(double)RAND_MAX+1)-.75; /* Offset */ 
    val = sin(2*PI*f*(i/8000)+phi) + r;      /* Noisy sine wave */
    printf("%f\n",val);                      /* Print values suitable to plot */
  }/*for*/
 
  return 0; /*exit program*/
}/*main*/

